version: '2'
services:
    mongo:
        image: mongo
        hostname: mongo
        ports:
            - '27017:27017'
    
    sharescraper-api:
        build: .
        image: andycowley/sharescraper-api
        hostname: sharescraper-api
        ports: 
            - '5000:5000'
        environment:
            MONGO: mongo